meta_product_name: "HiVie"
meta_title: "HiVie | HIV+ Dating App"
meta_description: "A safe space for HIV+ persons to  connect, share stories & find love"
meta_image: "cover.png" # should exist in `app/assets/images/`

